# Generated by Django 4.0.4 on 2022-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscribingott'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribingott',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribingott',
            name='share',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribingott',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
