# Generated by Django 4.0.4 on 2022-07-31 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_subscribingott_fee_alter_subscribingott_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribingott',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
