# Generated by Django 4.0.4 on 2022-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_start_date_subscribingott_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribingott',
            name='pay_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
