# Generated by Django 4.0.4 on 2022-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_subscribingott_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribingott',
            name='ott',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Disney Plus', 'Disney Plus'), ('Wavve', 'Wavve'), ('Prime Video', 'Prime Video'), ('Apple TV', 'Apple TV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
