# Generated by Django 4.0.4 on 2022-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_managers_alter_subscribingott_pay_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
