# Generated by Django 4.0.4 on 2022-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecontent',
            name='provider',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Disney Plus', 'Disney Plus'), ('wavve', 'Wavve'), ('Amazon Prime Video', 'Amazon Prime Video'), ('Apple TV Plus', 'Apple TV Plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='provider',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Disney Plus', 'Disney Plus'), ('wavve', 'Wavve'), ('Amazon Prime Video', 'Amazon Prime Video'), ('Apple TV Plus', 'Apple TV Plus')], max_length=20),
        ),
    ]
