# Generated by Django 4.0.6 on 2022-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvcontent',
            old_name='episode',
            new_name='total_episode',
        ),
        migrations.AddField(
            model_name='tvcontent',
            name='episode_status',
            field=models.IntegerField(default=0),
        ),
    ]
