# Generated by Django 4.0.4 on 2022-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_rename_episode_tvcontent_total_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecontent',
            name='provider',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Disney Plus', 'Disney Plus'), ('Wavve', 'Wavve'), ('Prime Video', 'Prime Video'), ('Apple TV', 'Apple TV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='provider',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Disney Plus', 'Disney Plus'), ('Wavve', 'Wavve'), ('Prime Video', 'Prime Video'), ('Apple TV', 'Apple TV')], max_length=20),
        ),
    ]
