# Generated by Django 4.0.4 on 2022-07-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towatchcontent',
            name='ott',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.subscribingott'),
        ),
        migrations.AddField(
            model_name='watchedcontent',
            name='ott',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.subscribingott'),
        ),
        migrations.AlterField(
            model_name='ott',
            name='fee',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
