# Generated by Django 4.0.6 on 2022-08-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_runtime', models.IntegerField()),
                ('ott', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subscribingott')),
            ],
        ),
    ]
