# Generated by Django 4.0.6 on 2022-08-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_subscribingott_ott'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='ott',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='account.subscribingott'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='total_runtime',
            field=models.IntegerField(default=0),
        ),
    ]
