# Generated by Django 4.0.4 on 2022-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_runtime_ott_alter_runtime_total_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='total_runtime',
            field=models.IntegerField(default=1),
        ),
    ]
